# Use an official Python runtime as a parent image
FROM python:3.6

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
#EXPOSE 80

# Define environment variable
ENV NAME World

ENV EVENT_HUB_CONNECTION_STR ''
ENV EVENT_HUB_NAME ''
ENV COSMOS_ACCOUNT_NAME ''
ENV COSMOS_PASSWORD ''
ENV COSMOS_DATABASE ''
ENV COSMOS_COLLECTION ''


# Run app.py when the container launches
CMD ["python", "monitor_mongo.py"]